name: NotJanselLive
version: 21w35a
main: de.notjansel.notjansellive.Main
api-version: 1.17
authors: [ NotJansel ]
description: Plugin, written for a Server, which name should not be called
website: https://twitch.tv/notjansel

commands:
  live:
    usage: /live
  offline:
    usage: /offline
  record:
    usage: /record
  finishrecord:
    usage: /finishrecord
  servertps:
    usage: /servertps
  configreload:
    usage: /configreload
    permission: notjansellive.reload

permissions:
  notjansellive.*:
    description: Access to every Plugin-command which needs a permission
    children:
      notjansellive.reload: true
  notjansellive.reload:
    description: Access to the Reload command